# -*- coding: utf-8 -*-
"""Book sentences for the How I Became a Ghost vocabulary, weeks 18-24.

q1 = Day 1 context sentence under the flip card
q2 = Day 2 Context Detective sentence (a second quote where the novel has one)
cloze = Day 3 fill-in-the-blank; {} marks where the word is removed
Every quote is verified against 'planning docs/hbg_ocr.txt' by tools/hbg_verify_quotes.py.
"""
S = {
 "Nahullo": ("Men rode horses from the river, Nahullo men, and they carried burning torches.",
             "The Nahullo men jumped on their horses and followed us.",
             "Men rode horses from the river, {} men, and they carried burning torches."),
 "missionaries": ("They leapt from their horses and threw the torches high, aiming for the house where the missionaries lived.",
             "The missionaries were visiting another Choctaw town that week, but the Nahullos didn’t know that.",
             "The {} were visiting another Choctaw town that week, but the Nahullos didn\u2019t know that."),
 "blowguns": ("With blowguns we caught our food.", None,
             "With {} we caught our food."),
 "torches": ("The torches made slow circles, turning over and over, followed by a trail of sparks.",
             "Like fiery comets, twenty flaming torches fell from the sky.",
             "The {} made slow circles, turning over and over, followed by a trail of sparks."),
 "smothering": ("I grabbed my blanket and wrapped it around my shoulders, smothering the flames.", None,
             "I grabbed my blanket and wrapped it around my shoulders, {} the flames."),
 "smallpox": ("How did she know the blankets carried smallpox?",
             "I had already seen smallpox, but I didn’t know it.",
             "How did she know the blankets carried {}?"),
 "belongings": ("Early the next morning we gathered our belongings and left the camp.", None,
             "Early the next morning we gathered our {} and left the camp."),
 "sickness": ("They died from sickness and they died from hunger.", None,
             "They died from {} and they died from hunger."),
 "refused": ("From that moment on, even though my feet burned, I refused to look behind me.", None,
             "Even though my feet burned, I {} to look behind me."),
 "vanished": ("The Choctaw ghosts vanished.", None,
             "The Choctaw ghosts {}."),
 "council": ("By nightfall we neared the council wagon.",
             "I wished I were the helper of the Choctaw Council, not a boy who would soon be a ghost.",
             "By nightfall we neared the {} wagon."),
 "treaty": ("That was what they agreed, at the Treaty Talk.",
             "That is what the treaty says,” Joseph said.",
             "That is what the {} says."),
 "invisible": ("I’ll be right with you, invisible as a ghost,” he joked.", None,
             "I’ll be right with you, {} as a ghost."),
 "determined": ("She is a determined little girl.", None,
             "She is a {} little girl."),
 "permission": ("My parents gave me permission to leave our camp,” I said.", None,
             "My parents gave me {} to leave our camp."),
 "courage": ("With my newfound courage, I walked to the soldiers’ campfire.", None,
             "With my newfound {}, I walked to the soldiers’ campfire."),
 "mourning": ("My mother started crying, a soft muffled cry that turned the blue and sunny day into one of quiet mourning.", None,
             "My mother started crying, a soft muffled cry that turned the blue and sunny day into one of quiet {}."),
 "terrified": ("A terrified young girl,” said another woman.", None,
             "A {} young girl,” said another woman."),
 "suffering": ("Will the suffering ever be over?", None,
             "Will the {} ever be over?"),
 "stickball": ("Each one held something, a blowgun, a boat paddle, a stickball bat, a cane fishing pole.", None,
             "Each one held something, a blowgun, a boat paddle, a {} bat, a cane fishing pole."),
 "bonepickers": ("When a Choctaw died, the body was brought to the bonepickers.",
             "Few Choctaws have ever seen the bonepickers, but everyone knew of them.",
             "When a Choctaw died, the body was brought to the {}."),
 "ancestors": ("That is the highest honor a Choctaw can ever earn, to make the ancestors proud.", None,
             "That is the highest honor a Choctaw can ever earn, to make the {} proud."),
 "distraction": ("We needed a distraction, and Jumper was ready to play.", None,
             "We needed a {}, and Jumper was ready to play."),
 "speechless": ("He stood speechless, his eyes filled with wonder.", None,
             "He stood {}, his eyes filled with wonder."),
 "honored": ("They spoke in a single voice and with a single word they honored us.", None,
             "They spoke in a single voice and with a single word they {} us."),
 "gratitude": ("On this morning I simply bowed my head like everyone else and whispered my gratitude.", None,
             "I simply bowed my head like everyone else and whispered my {}."),
 "prophecy": ("My prophecy comes true.", None,
             "My {} comes true."),
 "exhausted": ("I knew he was exhausted from the long day of rescuing Naomi, setting fire to the soldiers’ camp, rushing Naomi to the bonepickers’ wagon, and catching a raccoon with his bare teeth!", None,
             "I knew he was {} from the long day of rescuing Naomi."),
 "unconscious": ("Two councilmen rolled the limb away, and elderly Stella lay unconscious.", None,
             "Two councilmen rolled the limb away, and elderly Stella lay {}."),
 "revenge": ("His anger was strong, and I knew he would seek revenge in the morning.", None,
             "His anger was strong, and I knew he would seek {} in the morning."),
 "Pushmataha": ("We knew we would see General Pushmataha for many days and years to come.", None,
             "We knew we would see General {} for many days and years to come."),
 "protector": ("We met a new friend and protector that day, as well.", None,
             "We met a new friend and {} that day, as well."),
 "reunited": ("Naomi was reunited with her mother and father, and that very evening she insisted on helping with the cooking.", None,
             "Naomi was {} with her mother and father."),
 "survived": ("That is how you survived that night in the cave.", None,
             "That is how you {} that night in the cave."),
 "lifeless": ("He locked his jaws around the wolf’s head and lifted him off the ground, swinging him back and forth till the wolf was limp and lifeless.", None,
             "He lifted him off the ground, swinging him back and forth till the wolf was limp and {}."),
}
